// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "rest-api/models"

// ContactsService is an autogenerated mock type for the ContactsService type
type ContactsService struct {
	mock.Mock
}

// CreateContact provides a mock function with given fields: p
func (_m *ContactsService) CreateContact(p *models.Contact) error {
	ret := _m.Called(p)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Contact) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllContacts provides a mock function with given fields:
func (_m *ContactsService) GetAllContacts() ([]models.Contact, error) {
	ret := _m.Called()

	var r0 []models.Contact
	if rf, ok := ret.Get(0).(func() []models.Contact); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Contact)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetContact provides a mock function with given fields:
func (_m *ContactsService) GetContact() {
	_m.Called()
}
